apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: petclinic
  template:
    metadata:
      labels:
        io.kompose.service: petclinic
    spec:
      containers:
<<<<<<< HEAD
        - env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysqlserver/petclinic
            - name: SERVER_PORT
              value: "8080"
          image: 590184124193.dkr.ecr.ap-northeast-2.amazonaws.com/spring-petclinic-docker:1.7.1
          imagePullPolicy: IfNotPresent
          name: petclinic
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
=======
      - name: petclinic
        image: 590184124193.dkr.ecr.ap-northeast-2.amazonaws.com/spring-petclinic-docker:1.7.1
        ports:
        - containerPort: 8000
        - containerPort: 8080
        env:
        - name: MYSQL_URL
          value: jdbc:mysql://mysqlserver/petclinic
        - name: SERVER_PORT
          value: "8080"

>>>>>>> dc86720 (dsagwed)
